#+title: overview
#+startup: indent overview hideblocks entitiespretty

* Course Goal
- Learn to solve competitive programs on [[https://open.kattis.com/][Open Kattis]] platform.

- Learn to code efficiently and correctly
  - Pseudocode & keyboard-less coding practice to truly test knowledge of programming
  - Discovering new techniques - There's always something new to learn.

- Problem solving and coding in a using ~literate programming~ concepts
  In particular, I am very invested in learning to use relevant features in Emacs,
  in this and other courses like it. Failure to document code and preserve its context is a lost opportunity.

- Sharing what we've learned
  In the spirit of FOSS, sharing our knowledge with each-other makes us stronger computer scientists.

* Personal Learning Goals
- [ ] lambdas
- [ ] learn std::string
- [ ] multi-language competence
- [ ] Pointer operations

* Programming Literacy
Literacy includes /reading/ code. I think this is important for students to do, because
this skill otherwise wouldn't be obvious to improve until you're programming in a team.

Focusing on that skill more as a student ensures that one is more prepared to code efficiently
in a cooperative environment.

Basically, just read something complicated and try to reverse-engineer it. Somehow do that
but learn from it...  (There's not seemingly a whole lot of built offerings to do this)?

* Pro Tips:
** Header Guards

- This will prevent you from accidentally causing huge issues when you define functions in a .h file:
   #+begin_example cpp
   #ifndef VF_H
   #define VF_H
   ...
   #endif

   #+end_example

** Iterators:

Iterators are pointers... BUT they follow your dynamic array around the computer's memory,
because your pointer might change locations, because Vec does weird things under the hood
as it shrinks and expands... So, this is how you address that...

You want to use interators when you're writing C++ style code and avoid dropping down to
the regular pointers (which are C-style) whenever possible...

#+begin_example cpp
void everyOther(const std::vector<int>& vec) {
    std::vector<int> temp;
    std::vector<int>::iterator it;
    for (auto it=vec.cbegin(); it < vec.cend(); it+=2)
        temp.push_back(*it);
    return temp;
}

int first(const std::vector<int>& vec) {
    int min = *vec.begin();  //value fo vec[0]

}
#+end_example
