#+title: Lecture
#+startup: indent overview hideblocks entitiespretty
#+property: header-args:cpp :noweb yes :comments noweb :results output
#+property: header-args:python :noweb yes :comments noweb :results output

* Notes

* Canvas & Submission
** Pledge
#+name: pledge
#+begin_src cpp :noeval
// Matthew Younger (pledged)
#+end_src

#+name: pledge_py
#+begin_src python :noeval
# Matthew Younger (pledged)
#+end_src
** Post-mortem and Feedback:
#+begin_quote
I could tell that I hadn't programmed in Python in a while. Just like other students in the room,
I'd forgotten how to iterate without manually specifying range, incrementing i each for loop, etc.
Once I found my sea legs again, this was basically trivial. But, a good reminder that it's so easy to forget
past skills if they're not practiced often.

I do feel like I achieved my goal for the week, which was coding efficiently, but I feel rather like I took a shortcut using Python
over something more challenging. I'm a bit torn between the goals of the other class (to learn new techniques that are new to me)
and of this one - solve problems efficiently.

I learned that there's a huge difference between asking for a prompt solution to a problem, versus an optimized solution. The Kattis platform
analyzes both aspects of this, but I only focused on the first aspect.
#+end_quote

* Kattis/Ofugsnuid

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

#+name: ofugsnuid_py
#+begin_src python :noexec :tangle src/ofugsnuid.py
<<pledge_py>>

num_ints = int(input())
nums = []
for i in range(num_ints):
    nums.append(input())

for line in nums[::-1]:
    print(line)
#+end_src

* Kattis/Ofugsnuid Improved_bak

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

#+name: fn_printVecLines
#+begin_src cpp
// Description: Facilitates Efficient Printing of vec line-wise
void printVecLines(std::vector<int> vec){
    // it's more optimal to append a string 1\n2\n3\n... and print once.
    std::string outputString {};

    for (size_t index = 0; index < vec.size(); ++index) {
        outputString.append(std::to_string(vec[index]));
        outputString.push_back('\n');
    }

    // Print the string once:
    std::cout << outputString;
}
#+end_src

#+name: fn_reverseVec
#+begin_src cpp
// Description: Function prints reverse of supplied vec
void reverseVec(std::vector<int>& vec){
    // Grab vec.size(), it'll be used more than once
    size_t vecSize = vec.size();

    // leverage implicit conversion
    int reps = vecSize / 2;

    // Index value must persist across loops
    //   Specifically, the left index
    int index = 0;

    for (size_t i {}; i < vecSize; ++i) {
        int leftCopy = vec[index];

        // Replace left value with right
        vec[index] = vec[vecSize - index - 1];
        // Replace Right with left's copy
        vec[vecSize - index - 1] = leftCopy;

        // Move indices inward by 1
        ++index;
    }
}
#+end_src

#+name: ofugsnuid_cpp
#+begin_src cpp :noexec :tangle src/ofugsnuid.cpp
<<pledge>>

#include <iostream>
#include <vector>

// reverseVec definition:
void reverseVec(std::vector<int>&);

// printVecLines definition:
void printVecLines(std::vector<int>);

int main(){
    // Number of inputs user plans to send to vec
    int numInputs {};
    std::cin >> numInputs;

    // Empty vec to hold values, set to appropriate size:
    // Define size now for efficiency vs continually resizing it
    //   with each entry:
    std::vector<int> numberVec(numInputs);

    for (size_t i = 0; i < numInputs; ++i){
        std::cin >> numberVec[i];
    }

    // Call to our reversing func:
    reverseVec(numberVec);

    // Call to print the vector line-wise:
    printVecLines(numberVec);

    // Exit normally
    return 0;
}

<<fn_reverseVec>>
<<fn_printVecLines>>
#+end_src

#+RESULTS: ofugsnuid_cpp
: 4

#+name: test_
#+begin_src bash :results output
g++ src/ofugsnuid.cpp -o src/ofugsnuid
echo "3 10 12 9" | ./src/ofugsnuid
rm src/ofugsnuid
#+end_src

#+RESULTS: test_

* Kattis/Ofugsnuid Improved

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

I noticed an inconsistency in the problem.  It states that values could be up to 10bn, but this wouldn't be possible for
int to hold that large of a number?

I've tried everything I can think of and I can't optimize this better than 0.09 seconds.
#+end_src

#+name: ofugsnuid_cpp_improved
#+begin_src cpp :tangle src/ofugsnuid_improved.cpp :results output
<<pledge>>

#include <iostream>
#include <bits/stdc++.h>

/*
Pseudocode:

ask for size (n number of nums to be received)
allocate sizeof(int) * n byte block of memory

fill IN REVERSE...

cout normally i = 0, 1, 2...
,*/

int main(){

    // Trying to gain some efficiency (ChatGPT)
    // This alone seems to get the prog from 0.09 -> 0.03. BIG deal...
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);

    // ChatGPT also recommended:
    static char outbuf[1 << 20];
    std::cout.rdbuf()->pubsetbuf(outbuf, sizeof(outbuf));

    // First, figure out the amount of memory we need to reserve for the numbers that will be received
    int SIZE {};
    std::cin >> SIZE;

    // Now, we set aside n slots of memory
    unsigned long long* numbers = nullptr;
    numbers = new unsigned long long[SIZE]; // dynamically allocate memory...

    // NOTE: AI recommended an interesting thing for this for loop...
    //       It's not very readable, but I see what it's doing, and it seems neat...
    // Decrementing for loop, because we're adding to the array BACKWARDS
    // range of loop: [0,n)
    for (int index = SIZE; index-- > 0;) {
        // numbers[n]    Add to the array in this manner:
        // numbers[n-1]
        // ...
        // numbers[0]
        std::cin >> numbers[index];
    }

    // Now, we just need to print the values...
    //for (int index = 0; index < SIZE; ++index) {
    //    std::cout << numbers[index] << '\n';
    //}

    std::string buffer;
    buffer.reserve(static_cast<size_t>(SIZE) * 12);  // ~= 10 digits + /n?

    for(int i = 0; i < SIZE; ++i) {
        buffer += std::to_string(numbers[i]);
        buffer.push_back('\n');
    }

    // write all at once:
    std::cout << buffer;

    // ALWAYS free up the chunk of heap we borrowed...
    delete [] numbers;
    numbers = nullptr;

    // Exit normally
    return 0;
}
#+end_src

#+RESULTS: ofugsnuid_cpp_improved

#+name: test_ofugsnuid_improved
#+begin_src bash :results output
g++ src/ofugsnuid_improved.cpp -o src/ofugsnuid_improved
echo "5 1 2 3 4 5" | ./src/ofugsnuid_improved
rm src/ofugsnuid_improved
#+end_src

#+RESULTS: test_ofugsnuid_improved
: 5
: 4
: 3
: 2
: 1
