#+title: Lecture
#+startup: indent overview hideblocks entitiespretty
#+property: header-args:cpp :noweb yes :comments noweb :results output
#+property: header-args:python :noweb yes :comments noweb :results output

* Notes

* Canvas & Submission
** Pledge
#+name: pledge
#+begin_src cpp :noeval
// Matthew Younger (pledged)
#+end_src

#+name: pledge_py
#+begin_src python :noeval
# Matthew Younger (pledged)
#+end_src
** Post-mortem and Feedback:
#+begin_quote
I could tell that I hadn't programmed in Python in a while. Just like other students in the room,
I'd forgotten how to iterate without manually specifying range, incrementing i each for loop, etc.
Once I found my sea legs again, this was basically trivial. But, a good reminder that it's so easy to forget
past skills if they're not practiced often.

I do feel like I achieved my goal for the week, which was coding efficiently, but I feel rather like I took a shortcut using Python
over something more challenging. I'm a bit torn between the goals of the other class (to learn new techniques that are new to me)
and of this one - solve problems efficiently.

I learned that there's a huge difference between asking for a prompt solution to a problem, versus an optimized solution. The Kattis platform
analyzes both aspects of this, but I only focused on the first aspect.
#+end_quote

* Kattis/Ofugsnuid

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

#+name: ofugsnuid_py
#+begin_src python :noexec :tangle src/ofugsnuid.py
<<pledge_py>>

num_ints = int(input())
nums = []
for i in range(num_ints):
    nums.append(input())

for line in nums[::-1]:
    print(line)
#+end_src
