#+title: Lecture
#+startup: indent overview hideblocks entitiespretty
#+property: header-args:cpp :noweb yes :comments noweb :results output
#+property: header-args:python :noweb yes :comments noweb :results output

* Notes

* Canvas & Submission
** Pledge
#+name: pledge
#+begin_src cpp :noeval
// Matthew Younger (pledged)
#+end_src

#+name: pledge_py
#+begin_src python :noeval
# Matthew Younger (pledged)
#+end_src
** Post-mortem and Feedback:
#+begin_quote
I could tell that I hadn't programmed in Python in a while. Just like other students in the room,
I'd forgotten how to iterate without manually specifying range, incrementing i each for loop, etc.
Once I found my sea legs again, this was basically trivial. But, a good reminder that it's so easy to forget
past skills if they're not practiced often.

I do feel like I achieved my goal for the week, which was coding efficiently, but I feel rather like I took a shortcut using Python
over something more challenging. I'm a bit torn between the goals of the other class (to learn new techniques that are new to me)
and of this one - solve problems efficiently.

I learned that there's a huge difference between asking for a prompt solution to a problem, versus an optimized solution. The Kattis platform
analyzes both aspects of this, but I only focused on the first aspect.
#+end_quote

* Kattis/Ofugsnuid

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

#+name: ofugsnuid_py
#+begin_src python :noexec :tangle src/ofugsnuid.py
<<pledge_py>>

num_ints = int(input())
nums = []
for i in range(num_ints):
    nums.append(input())

for line in nums[::-1]:
    print(line)
#+end_src

* Kattis/Ofugsnuid Improved_bak

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

#+name: fn_printVecLines
#+begin_src cpp
// Description: Facilitates Efficient Printing of vec line-wise
void printVecLines(std::vector<int> vec){
    // it's more optimal to append a string 1\n2\n3\n... and print once.
    std::string outputString {};

    for (size_t index = 0; index < vec.size(); ++index) {
        outputString.append(std::to_string(vec[index]));
        outputString.push_back('\n');
    }

    // Print the string once:
    std::cout << outputString;
}
#+end_src

#+name: fn_reverseVec
#+begin_src cpp
// Description: Function prints reverse of supplied vec
void reverseVec(std::vector<int>& vec){
    // Grab vec.size(), it'll be used more than once
    size_t vecSize = vec.size();

    // leverage implicit conversion
    int reps = vecSize / 2;

    // Index value must persist across loops
    //   Specifically, the left index
    int index = 0;

    for (size_t i {}; i < vecSize; ++i) {
        int leftCopy = vec[index];

        // Replace left value with right
        vec[index] = vec[vecSize - index - 1];
        // Replace Right with left's copy
        vec[vecSize - index - 1] = leftCopy;

        // Move indices inward by 1
        ++index;
    }
}
#+end_src

#+name: ofugsnuid_cpp
#+begin_src cpp :noexec :tangle src/ofugsnuid.cpp
<<pledge>>

#include <iostream>
#include <vector>

// reverseVec definition:
void reverseVec(std::vector<int>&);

// printVecLines definition:
void printVecLines(std::vector<int>);

int main(){
    // Number of inputs user plans to send to vec
    int numInputs {};
    std::cin >> numInputs;

    // Empty vec to hold values, set to appropriate size:
    // Define size now for efficiency vs continually resizing it
    //   with each entry:
    std::vector<int> numberVec(numInputs);

    for (size_t i = 0; i < numInputs; ++i){
        std::cin >> numberVec[i];
    }

    // Call to our reversing func:
    reverseVec(numberVec);

    // Call to print the vector line-wise:
    printVecLines(numberVec);

    // Exit normally
    return 0;
}

<<fn_reverseVec>>
<<fn_printVecLines>>
#+end_src

#+RESULTS: ofugsnuid_cpp

#+name: test_
#+begin_src bash :results output
g++ src/ofugsnuid.cpp -o src/ofugsnuid
echo "3 10 12 9" | ./src/ofugsnuid
rm src/ofugsnuid
#+end_src

#+RESULTS: test_

* Kattis/Ofugsnuid Improved

[[https://open.kattis.com/problems/ofugsnuid][Link to Problem]]

I've tried everything I can think of and I can't optimize this better than 0.09 seconds.

#+name: fn_printVecRev
#+begin_src cpp
// Description: Facilitates Efficient Printing of vec line-wise
void printVecRev(std::vector<int> vec){
    for (auto it = vec.rbegin(); it != vec.rend(); ++it) {
        std::cout << *it << '\n';
    }
}
#+end_src

#+name: ofugsnuid_cpp
#+begin_src cpp :noexec :tangle src/ofugsnuid_improved.cpp
<<pledge>>

#include <iostream>
#include <vector>

// printVecLines definition:
void printVecRev(std::vector<int>);

int main(){
    // Number of inputs user plans to send to vec
    int numInputs {};
    std::cin >> numInputs;

    // Empty vec to hold values, set to appropriate size:
    // Define size now for efficiency vs continually resizing it
    //   with each entry:
    std::vector<int> numberVec(numInputs);

    for (size_t i = 0; i < numInputs; ++i){
        std::cin >> numberVec[i];
    }

    // Call to print the vector reversed line-wise:
    printVecRev(numberVec);

    // Exit normally
    return 0;
}

<<fn_printVecRev>>
#+end_src

#+RESULTS: ofugsnuid_cpp

#+name: test_new
#+begin_src bash :results output
g++ src/ofugsnuid_improved.cpp -o src/ofugsnuid_improved
echo "3 10 12 9" | ./src/ofugsnuid_improved
rm src/ofugsnuid_improved
#+end_src

#+RESULTS: test_new
: 9
: 12
: 10

#+name: ofugsnuid_rs
#+begin_src rust :tangle src/ofugsnuid.rs
use std::io::{self, BufRead};

fn main() {
    let stdin = io::stdin();
    let handle = stdin.lock();

    // Read the first line, which indicates the number of entries
    let mut lines = handle.lines();
    let num_inputs: usize = lines.next().unwrap().unwrap().parse().unwrap();

    // Initialize a vector to hold the numbers
    let mut number_vec: Vec<i32> = Vec::with_capacity(num_inputs);

    // Read the following numbers
    for _ in 0..num_inputs {
        let line = lines.next().unwrap().unwrap();
        let number: i32 = line.parse().unwrap();
        number_vec.push(number);
    }

    // Reverse the vector
    number_vec.reverse();

    // Print each number in the reversed vector
    for number in number_vec {
        println!("{}", number);
    }
}
#+end_src

#+name: test_ofugsnuid_rs
#+begin_src bash :results output
rustc -o src/ofugsnuid_rs src/ofugsnuid.rs
echo -e "5\n1\n2\n3\n4\n5\n" | ./src/ofugsnuid_rs
rm src/ofugsnuid_rs
#+end_src

#+RESULTS: test_ofugsnuid_rs
: 5
: 4
: 3
: 2
: 1
